### ISSUE TITLE
Usability Review

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore-playground#33]
We gathered some feedback from two programmers we showed this app to:

# Permalink
* [ ] CRITICAL: Both didn't notice it, one of them thought it was for sharing on social media. [#34](https://github.com/bitpay/bitcore-playground/issues/34)

# Console
* [x] CRITICAL: Both didn't notice it

# Keys
* [x] CRITICAL: `PrivateKey.isValid` only checks for WIF format (no hex)
* [x] HIGH: One did not notice the code example is dynamic. [#38](https://github.com/bitpay/bitcore-playground/pull/38)
* [x] HIGH: It was not clear that he could paste a private key on the inputs. [#48](https://github.com/bitpay/bitcore-playground/pull/48)
* [x] LOW: Did't recognize the "dice button" as "new key"
* [x] ?: He thought that the example was not behaving as expected when pasting a private key and generating a random key

# Multisig
* [x] HIGH: He was against the "horizontality" of the interface. Maybe put "Address" on top?

# HDKeys
* [x] CRITICAL: He did not understand this screen at all -- I had to show him that he could edit the path (the input box was too gray, he thought it couldn't be modified.
